# Generated by Django 5.2.12 on 2026-04-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Адрес доставки'),
        ),
    ]
