# Generated by Django 5.2.12 on 2026-04-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_address_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveBigIntegerField(default=0, verbose_name='Всего просмотров')),
            ],
            options={
                'verbose_name': 'счётчик посещений',
                'verbose_name_plural': 'счётчик посещений',
            },
        ),
    ]
