# Generated by Django 5.2.13 on 2026-04-22 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_visit_counter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, default='', max_length=600, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Текст статьи')),
                ('tag', models.CharField(blank=True, default='Статья', max_length=80, verbose_name='Категория')),
                ('reading_time_minutes', models.PositiveSmallIntegerField(default=8, verbose_name='Время чтения (мин)')),
                ('cover_image', models.CharField(blank=True, default='', help_text='Например: images/news/model11.JPEG', max_length=255, verbose_name='Обложка (путь в static/)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
