# Generated by Django 5.2.12 on 2026-04-22 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_restore_full_news_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('shop', 'Магазин (платный)'), ('free', 'Бесплатная модель')], db_index=True, default='shop', max_length=10, verbose_name='Тип карточки')),
                ('file_type', models.CharField(choices=[('3d', '3D модель'), ('2d', '2D файл'), ('other', 'Другое')], default='3d', max_length=10, verbose_name='Тип файла')),
                ('free_category', models.CharField(blank=True, choices=[('hobby', 'Хоббийные модели'), ('art', 'Художественные модели'), ('tech', 'Технические модели')], default='', help_text='Определяет, в каком табе страницы /free_models/ показывать карточку.', max_length=10, verbose_name='Таб (только для бесплатных)')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', help_text='Простой текст; переводы строки в шаблоне превращаются в <br>.', verbose_name='Описание')),
                ('badge', models.CharField(blank=True, default='', help_text='Короткая метка на карточке (например, «NEW»). Пусто — без бейджа.', max_length=80, verbose_name='Бейдж')),
                ('image', models.CharField(help_text='Например: images/shop/battletoad.png', max_length=500, verbose_name='Главная картинка (путь в static/)')),
                ('alt', models.CharField(blank=True, default='', max_length=200, verbose_name='Alt для главной картинки')),
                ('price_rub', models.PositiveIntegerField(default=0, help_text='Целое число в рублях. Для бесплатных — 0.', verbose_name='Цена, ₽')),
                ('download_url', models.CharField(blank=True, default='', help_text='Для бесплатных моделей: полный URL (https://…) или относительный путь в static/ (files/free/xxx.zip).', max_length=500, verbose_name='Ссылка на скачивание')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Опубликовано')),
                ('is_sold_out', models.BooleanField(default=False, help_text='Показывать метку «Нет в продаже» и блокировать кнопку купить/скачать.', verbose_name='Распродано')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Меньшее число — карточка выше на странице.', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'товар / бесплатная модель',
                'verbose_name_plural': 'товары и бесплатные модели',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(help_text='Например: images/shop/free/peper2.png', max_length=500, verbose_name='Путь к картинке (в static/)')),
                ('alt', models.CharField(blank=True, default='', max_length=200, verbose_name='Alt-текст')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'доп. ракурс',
                'verbose_name_plural': 'доп. ракурсы',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
