# Generated by Django 5.2.12 on 2026-04-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_seed_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_placeholder',
            field=models.BooleanField(default=False, help_text='Рендерить пустую карточку «Скоро новая модель» вместо обычной. Можно не заполнять image / description / download_url. Карточка не попадает в корзину и превью на главной.', verbose_name='Placeholder «Скоро»'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, default='', help_text='Например: images/shop/battletoad.png. Для placeholder-карточки можно оставить пустым.', max_length=500, verbose_name='Главная картинка (путь в static/)'),
        ),
    ]
