# Generated by Django 5.2.12 on 2026-04-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_product_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='free_category',
            field=models.CharField(blank=True, choices=[('art', 'Художественные модели'), ('hobby', 'Хоббийные модели'), ('tech', 'Технические модели')], default='', help_text='Определяет, в каком табе страницы /free_models/ показывать карточку.', max_length=10, verbose_name='Таб (только для бесплатных)'),
        ),
    ]
