# Generated by Django 5.2.13 on 2026-09-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_seed_coin_minting_news_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='contact_email_allowed_domains',
            field=models.CharField(blank=True, default='ru, com, icloud.com, me', help_text='Домены или суффиксы через запятую. Домен письма должен совпадать или заканчиваться на один из них: ru → mail.ru, com → gmail.com, icloud.com, me → proton.me.', max_length=500, verbose_name='Разрешённые домены'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_email_domain_mode',
            field=models.CharField(choices=[('any', 'Любой домен'), ('whitelist', 'Только разрешённые домены')], db_index=True, default='any', help_text='«Только разрешённые» — сообщения принимаются лишь с адресов на доменах из списка ниже.', max_length=20, verbose_name='Фильтр доменов почты'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_form_enabled',
            field=models.BooleanField(default=True, help_text='Выключите, чтобы скрыть контактные формы на сайте и блокировать отправку сообщений (POST на главную и /about/ отклоняется).', verbose_name='Приём сообщений с сайта'),
        ),
    ]
