# Generated by Django 5.2.13 on 2026-09-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_sitesetting_contact_email_allowed_domains_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseBucket',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
