// Run: node scripts/test-scales.cjs. No browser or npm dependencies required.
const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const zlib = require('node:zlib');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, '../static/js/scales_generator.js'), 'utf8');
const context = { Blob, TextEncoder, document: { readyState: 'loading', addEventListener() {} }, window: { addEventListener() {} } };
vm.createContext(context);
// Expose the private encoders only inside this isolated test VM.
vm.runInContext(source.replace(/\}\)\(\);\s*$/, 'globalThis.engine = {savePng, saveTiff32Float, getScaleHeight};})();'), context);
const s = { width: 257, height: 129, columns: 7, rows: 9, shape: 1, direction: 0,
    overlap: 0.15, stagger: 0.5, gamma: 1, minimum: 0, maximum: 1,
    invert: false, smooth: false, bits: 16, curvePoints: [{x: 0, y: 0}, {x: 1, y: 1}] };
async function main() {
    const png = Buffer.from(await context.engine.savePng(s).arrayBuffer());
    assert.equal(png.subarray(1, 4).toString(), 'PNG');
    assert.equal(png.readUInt32BE(16), s.width);
    assert.equal(png[24], 16);
    assert.equal(png[25], 0); // grayscale
    let pos = 8, raw;
    while (pos < png.length) {
        const length = png.readUInt32BE(pos);
        const type = png.subarray(pos + 4, pos + 8).toString();
        const data = png.subarray(pos + 8, pos + 8 + length);
        assert.equal(zlib.crc32(png.subarray(pos + 4, pos + 8 + length)), png.readUInt32BE(pos + 8 + length));
        if (type === 'IDAT') raw = zlib.inflateSync(data);
        pos += length + 12;
    }
    assert.equal(raw.length, (1 + s.width * 2) * s.height);
    const values = new Set();
    for (let y = 0; y < s.height; y++) {
        assert.equal(raw[y * (s.width * 2 + 1)], 0);
        for (let x = 0; x < s.width; x++) values.add(raw.readUInt16BE(y * (s.width * 2 + 1) + 1 + x * 2));
    }
    assert.ok(values.size > 256, 'The PNG must retain more than 8-bit precision');
    const tiff = Buffer.from(await context.engine.saveTiff32Float(s).arrayBuffer());
    assert.equal(tiff.readUInt16LE(2), 42);
    assert.equal(tiff.readUInt16LE(8), 15);
    const tags = {};
    for (let offset = 10; offset < 190; offset += 12) tags[tiff.readUInt16LE(offset)] = tiff.readUInt32LE(offset + 8);
    assert.equal(tags[258], 32);
    assert.equal(tags[339], 3); // IEEE float
    assert.equal(tiff.readUInt32LE(190), 0); // no next IFD
    assert.equal(tags[273] + tags[279], tiff.length);
    for (let offset = tags[273]; offset < tiff.length; offset += 4) {
        const value = tiff.readFloatLE(offset);
        assert.ok(Number.isFinite(value) && value >= 0 && value <= 1);
    }
    for (let shape = 0; shape < 4; shape++) for (let direction = 0; direction < 4; direction++) {
        const settings = {...s, shape, direction};
        assert.ok(Math.abs(context.engine.getScaleHeight(0.13, 0.37, settings) - context.engine.getScaleHeight(1.13, 1.37, settings)) < 1e-10);
    }
    // Optional reproducible preview asset, generated by the actual application.
    if (process.argv[2]) fs.writeFileSync(process.argv[2], png);
    console.log(`PASS: 16-bit PNG (${values.size} levels, CRC/DEFLATE), float TIFF (15 tags), 16 tiling configurations`);
}
main().catch(err => { console.error(err); process.exitCode = 1; });
